app:
  weather-api:
    token: ${WEATHER_API_TOKEN}
spring:
  datasource:
      url: jdbc:h2:mem:weather_application
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:changelog/main-db-changelog.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none