app:
  weather-api:
    token: ${WEATHER_API_TOKEN}
  weather-repository:
    implementation: WeatherJpaRepository
spring:
  datasource:
      url: jdbc:h2:mem:weather_application;NON_KEYWORDS=user
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driverClassName: org.h2.Driver
  h2:
    console:
      enabled: false
  liquibase:
    change-log: classpath:changelog/main-db-changelog.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none